# Generated by Django 2.0.3 on 2018-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('SO', models.CharField(max_length=200)),
                ('SNMP_version', models.CharField(max_length=200)),
                ('system_location', models.CharField(max_length=200)),
                ('interfaces', models.CharField(max_length=200)),
                ('community', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('host_name', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=200)),
            ],
        ),
    ]
